# fanout binding default
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: queue.log.messages.output
          binder: local_rabbit
        anotherOutput:
          destination: queue.log.messages.anotherOutput
          binder: local_rabbit
          # consumers in the same will consume the same queue
          group: logMessageConsumers
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
server:
  port: 0
management:
  health:
    binders:
      enabled: true